### ISSUE TITLE
Workflow on polyfill

### ISSUE THREAD

**Issue by jdelhommeau** [microsoft/PARAKEET#10]
Hi @mehulparsana ,

Apologies as this was likely discussed during previous PARAKEET call, but I couldn't attend, so I wanted to clarify what is the expected behavior for ongoing test with polyfill.

Is the polyfill workflow already including the parakeet service, or is the polyfill js script emulating the parakeet service client and making direct call to the ad-network?

Looking at the code in Parakeet.Polyfill.ts

It seems the `createAdRequest ` makes a direct call form the page to "https://edge.microsoft.com/.well-known/ad-bundles" url. According to the parakeet spec, it seems that the ".well-known/ad-bundles" endpoint is the ad-network endpoint that parakeet service would call. So my understanding is that in the polyfill test phase, there is no actual parakeet service needed, this is all emulated by the polyfill.

Correct?

Does it also means that any SSP that would like to test should update his own version of parakeet.polyfill.ts to use his own endpoint (rather than microsoft's one) ?

Thank you for your help clarifying above points.

**Comment by Brandr0id** [comment]
@jdelhommeau  the edge.microsoft.com endpoint is the evaluation version of the PARAKEET service and should remain intact. The SSP endpoint should be specified as the proxiedAnonymizingOrigin in the [adRequestConfig](https://github.com/microsoft/PARAKEET/tree/main/Polyfill#adrequestconfig). The service will ensure the SSP's .well-known/ad-bundles endpoint is in turn called as appropriate.

**Comment by jdelhommeau** [comment]
Thank you @Brandr0id , that makes sense. The confusion I had came from the fact that the edge.microsoft.com endpoint was using the same url schema (/.well-known/ad-bundles) as the one SSPs should implement to be called by parakeet service.
To make sure I now have this right: Microsoft is hosting his own version of an initial parakeet server, which will be called by the polyfill script with provided adConfig. AdConfig will contain the final SSP to be called by microsoft hosted parakeet server.
Correct?
Does it mean Microsoft will proxy 100% of the ad call during that test phase? Or will others be able to build their own version of a parakeet server and have polyfill use it?

**Comment by erik-anderson** [comment]
@jdelhommeau: Yes, Microsoft is hosting the PARAKEET server for this test phase. The ad config you pass will contain the endpoint for the PARAKEET server to relay requests to.

Longer term, we're still evaluating if there are reasonable options to have someone other than the browser vendor run a PARAKEET-like service. We are investing significant engineering resources into the service we're standing up, the functionality and proposals will continue to evolve, and there are many outstanding governance questions. So, for the foreseeable future you should assume Microsoft will be providing the proxying service (for the polyfill implementation and when the functionality is natively available in Microsoft Edge).

**Comment by jdelhommeau** [comment]
thank you @erik-anderson , that makes perfect sense.
